### ISSUE TITLE
Add pagination to the table

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/ruby_on_rails_whatsapp_example#1]
The current table in messages/index is not paginated.

In order to make it paginated a few changes are needed:
- [ ] [`Messages#index function`](https://github.com/ignacio-chiazzo/ruby_on_rails_whatsapp_example/blob/main/app/controllers/messages_controller.rb#L5) needs to accept a page ID and return the items on that page.
- [ ] The [view](https://github.com/ignacio-chiazzo/ruby_on_rails_whatsapp_example/blob/d0be04513434f28f85b5d1ec71a70ba7e97eefe7/app/views/messages/index.html.erb#L15) needs to implement pagination. 

Resources:
- This [blog post](https://dev.to/eclecticcoding/rails-pagination-with-tailwind-326n) explains pagination with Tailwind & Rails.

**Comment by areesha-sayed** [comment]
I would like to work on this. Please assign it to me.

**Comment by ignacio-chiazzo** [comment]
Sure!

**Comment by sahilbansal17** [comment]
@error707-persona Are you still working on it? @ignacio-chiazzo Can I pick it up in case @error707-persona is not working on the same?

**Comment by ignacio-chiazzo** [comment]
Go for it @sahilbansal17

**Comment by sahilbansal17** [comment]
@ignacio-chiazzo Please review the PR when you get time. :)
https://github.com/ignacio-chiazzo/ruby_on_rails_whatsapp_example/pull/2
